# .readthedocs.yaml (version 2)
version: 2

build:
  environment:
    GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}

sphinx:
  configuration: docs/conf.py

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

